### ISSUE TITLE
tour: ตัวห้อยคืออะไรครับ ? 

### ISSUE THREAD

**Issue by panudetjt** [gogetth/tour#7]
Context: https://go-tour-th.appspot.com/flowcontrol/8

จาก [ตัวยกและตัวห้อย](https://th.wikipedia.org/wiki/%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%A2%E0%B8%81%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%AB%E0%B9%89%E0%B8%AD%E0%B8%A2) เขาบอกว่าตัวห้อย (subscript) ในทางคณิตศาตร์ หมายถึงเลขฐาน 

ทาง [ต้นทาง](https://tour.golang.org/flowcontrol/8) ก็ไม่มีการใช้การเขียนสมการอะไรนะครับ

ผมเพิ่งเริ่มเรียนภาษา Go กับไม่มีพื้นฐานคณิตศาตร์ครับ 

ขอบคุณครับ

**Comment by chonla** [comment]
ตัวห้อยในที่นี้หมายถึง index ครับ

cc: @pallat เนื้อหาที่แปลต่างจากต้นฉบับอยู่พอสมควร อยากจะแปลให้ใกล้เคียงกับต้นฉบับมากขึ้นไหมครับ หรือแบบนี้โอเคแล้วครับ

**Comment by suksit** [comment]
ความเห็นส่วนตัว ผมว่าควรแปลให้ใกล้เคียงต้นฉบับครับ วัตถุประสงค์ของ exercise นี้คือฝึกการใช้ loop กับ function ไม่ใช่ฝึกการแปลงสมการเป็นโค้ด หรือสอน Newton Method

**Comment by chonla** [comment]
ขอบคุณครับ

**Comment by chonla** [comment]
FYI ทุกท่าน

จริง ๆ เนื้อหาในส่วนนี้แปลตามต้นฉบับถูกต้องแล้ว แต่ตัวที่เป็นเวอร์ชั่นภาษาอังกฤษ มีการอัพเดทเนื้อหา โดยตัดส่วนที่พูดถึงนิวตันออกไป และปรับปรุงเนื้อหาใหม่นะครับ

เดี๋ยวจะลองอัพเดทเนื้อหาให้ตรงกับเวอร์ชั่นล่าสุดนะครับ

**Comment by chonla** [comment]
done 086eb8946a9f2fd9299898416bdaabbb27810457
